### ISSUE TITLE
All n-level submenus share a single shortcut enumeration

### ISSUE THREAD

**Issue by mfaizsyahmi** [gyng/save-in#198] opened 2023-01-31 09:26 UTC
Suppose I have this menu layout:

- Item A
    - Subitem A1
        - Item A1i
        - Item A1ii
    - SubItem A2
        - Item A2i
        - Item A2ii
- Item B
    - SubItem B1
    - SubItem B2
        - Item B2i
- Item C

The logical thing is to have the subitem and sub-sub-item counter reset on each new parent. In the example above the third level enumeration for A2 starts at i, then ii, etc.

But the extension currently uses a single enumeration for every level, that crosses the parent items such that the orders are as follows:

- Item A
    - Subitem A1
        - Item A1i
        - Item A1ii
    - SubItem A2
        - Item A2iii
        - Item A2iv
- Item B
    - SubItem B3
    - SubItem B4
        - Item B4v
- Item C

The ordering (for the purpose of the numbered shortcuts) should have been like in the first example. Having the ordering as it is in the second example means numbered shortcuts breaks if you have more than 10 items across any menu level, because you have &11, &12, &13, etc. all having the same shortcut character (number 1).

I'm not filing this issue under [Feature Request] as I consider the current behavior a bug, one that people have learned to live with. It would break muscle memory if this get fixed but it'd be way more functional.

**Comment by gyng** [comment] 2023-02-10 18:22
Released in v3.7.0. Please re-open if the issue is still not fixed. Extension storefronts might take some time to update.

Thanks for your contribution!

**Closed by gyng** 2023-02-10 18:22 UTC
