### ISSUE TITLE
Feature request: add ability to save current page as a link

### ISSUE THREAD

**Issue by CottonEaster** [gyng/save-in#17] opened 2017-11-11 18:37 UTC
The non-webExtension addOn [SaveLink](https://addons.mozilla.org/en-US/firefox/addon/savelink/) allows one to save the current page as a link. That function is very convenient. I'd love to see it in your excellent addOn.

**Comment by gyng** [comment] 2017-11-12 18:43
This will have to be a separate extension, I think. Will have to write shortcut files manually.

**Comment by gyng** [comment] 2017-11-29 11:45
Landed in 1.6.0. Please reopen if it doesn't seem to work as intended.

**Closed by gyng** 2017-11-29 11:45 UTC
Labels: feature request
