### ISSUE TITLE
Option to skip saving duplicates

### ISSUE THREAD

**Issue by Power-Fusion** [gyng/save-in#35] opened 2017-11-29 04:40 UTC
Hi, Ive moved to your plugin since the Firefox update and have found it perfect for what I need. However I was wondering if you would be able to add a checkbox for saving duplicates? As currently it will save no matter what and I would prefer the option to bring up the replace dialog, or skip the download all together.
Thanks.

**Comment by gyng** [comment] 2017-11-29 08:57
Duplicate of #18. It's not available in Firefox, but an option will be coming in Chrome real soon!

**Closed** 2017-11-29 09:02 UTC
